[project]
name = "data-cubes-arceme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=2.0,<3.0",
    "planetary-computer>=1.0.0",
    "pyproj>=3.7.2",
    "pystac-client>=0.9.0",
    "python-dateutil>=2.9.0.post0",
    "pyyaml>=6.0.3",
    "rasterio>=1.4.4",
    "requests>=2.32.5",
    "senseiv2",
    "shapely>=2.1.2",
    "stackstac>=0.5.1",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "xarray>=2026.2.0",
    "zarr<3.0",
]

[tool.uv.sources]
senseiv2 = { git = "https://github.com/aliFrancis/SEnSeIv2.git" }
